on: push

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          jq '.event' "$GITHUB_CONTEXT"
          echo "$GITHUB_CONTEXT"
