on: push

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" > github-context.json
          jq '.event.commits[0] | { message: .message, stamp: .timestamp }' github-context.json
