on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "${{toJson(github)}}" | tee github-context.json
          jq '.event.commits[0] | { message: .message, stamp: .timestamp }' github-context.json
